server:
    error:
        include-message: always
        include-stacktrace: never
    port: 8005
spring:
    application:
        name: category-service
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: root
        url: jdbc:mysql://localhost/zhoppy?useSSL=false
        username: root
