service:
    port: 8001
    error:
        include-stacktrace: never
        include-message: always

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost/zhoppy?useSSL=false
    dbname: zhoppy
    password: root