server:
    port: 8070
spring:
    cloud:
        config:
            server:
                git:
                    default-label: Feignclient-feature
                    uri: https://github.com/NastMz/Backend-Ing-Software
                    search-path: config-data
    application:
        name: config-service